name: "自动获取最新网易新闻热点"
on:
  push:
  schedule:
    # 每天早上8点运行
    - cron: "0 8 * * *"
jobs:
  get-news:
    runs-on: ubuntu-latest
    steps:
      - name: "检查仓库"
        uses: actions/checkout@v3
      - name: "编译程序"
        run: |
          git checkout master
          git config --global user.email "cnwwhai@gmail.com"
          git config --global user.name "wwhai"
          go run main.go

      - name: 启动提交
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: wwhai
          author_email: cnwwhai@gmail.com
          message: "$(date)"
          add: 'index.md'