name: "自动获取最新网易新闻热点"
on:
  push:
  schedule:
    # 每天早上8点运行
    - cron: "0 8 * * *"
jobs:
  get-news:
    runs-on: ubuntu-latest
    steps:
      - name: "检查仓库"
        uses: actions/checkout@v1
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: wwhai
          author_email: cnwwhai@gmail.com
          message: "$(date)"
          add: 'index.md'

