name: "自动获取最新网易新闻热点"
on:
  push:
  schedule:
    # 每天早上8点运行
    - cron: "0 8 * * *"
jobs:
  get-news:
    runs-on: ubuntu-latest
    steps:
      - name: "检查仓库"
        uses: actions/checkout@v1
      - name: "编译程序"
        run: |
          git checkout master
          git config --global user.email "cnwwhai@gmail.com"
          git config --global user.name "wwhai"
          go run main.go
          git add index.md
          git commit -m "$(date)"
          git branch -v
          git remote -v
          git push origin master
