name: "自动获取最新网易新闻热点"
on:
  push:
  schedule:
    # 每天早上8点运行
    - cron: "0 8 * * *"
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "检查仓库"
        uses: actions/checkout@v1
      - name: "编译程序"
        run: |
          go run main.go
          git add index.md
          git commit -m "$(date)"
          git push
